#!/bin/bash
# Generate Neovim base16 colors file

generate_neovim_colors() {
    local theme_file="$1"
    local output_file="$2"

    # Read base16 colors
    local base00=$(read_toml "$theme_file" "colors.base16" "base00")
    local base01=$(read_toml "$theme_file" "colors.base16" "base01")
    local base02=$(read_toml "$theme_file" "colors.base16" "base02")
    local base03=$(read_toml "$theme_file" "colors.base16" "base03")
    local base04=$(read_toml "$theme_file" "colors.base16" "base04")
    local base05=$(read_toml "$theme_file" "colors.base16" "base05")
    local base06=$(read_toml "$theme_file" "colors.base16" "base06")
    local base07=$(read_toml "$theme_file" "colors.base16" "base07")
    local base08=$(read_toml "$theme_file" "colors.base16" "base08")
    local base09=$(read_toml "$theme_file" "colors.base16" "base09")
    local base0A=$(read_toml "$theme_file" "colors.base16" "base0A")
    local base0B=$(read_toml "$theme_file" "colors.base16" "base0B")
    local base0C=$(read_toml "$theme_file" "colors.base16" "base0C")
    local base0D=$(read_toml "$theme_file" "colors.base16" "base0D")
    local base0E=$(read_toml "$theme_file" "colors.base16" "base0E")
    local base0F=$(read_toml "$theme_file" "colors.base16" "base0F")

    # Create parent directory if needed
    mkdir -p "$(dirname "$output_file")"

    cat > "$output_file" << EOF
-- Auto-generated by set-theme.sh - DO NOT EDIT
return {
  base16 = {
    base00 = "#$base00",
    base01 = "#$base01",
    base02 = "#$base02",
    base03 = "#$base03",
    base04 = "#$base04",
    base05 = "#$base05",
    base06 = "#$base06",
    base07 = "#$base07",
    base08 = "#$base08",
    base09 = "#$base09",
    base0A = "#$base0A",
    base0B = "#$base0B",
    base0C = "#$base0C",
    base0D = "#$base0D",
    base0E = "#$base0E",
    base0F = "#$base0F",
  }
}
EOF
}
