#!/bin/bash
# Generate WezTerm colors file

generate_wezterm_colors() {
    local theme_file="$1"
    local output_file="$2"

    # Read colors from TOML
    local bg=$(read_toml "$theme_file" "colors" "background")
    local fg=$(read_toml "$theme_file" "colors" "foreground")
    local cursor_bg=$(read_toml "$theme_file" "colors.cursor" "background")
    local cursor_fg=$(read_toml "$theme_file" "colors.cursor" "foreground")
    local sel_bg=$(read_toml "$theme_file" "colors.selection" "background")
    local sel_fg=$(read_toml "$theme_file" "colors.selection" "foreground")

    # Terminal colors
    local black=$(read_toml "$theme_file" "colors.terminal" "black")
    local red=$(read_toml "$theme_file" "colors.terminal" "red")
    local green=$(read_toml "$theme_file" "colors.terminal" "green")
    local yellow=$(read_toml "$theme_file" "colors.terminal" "yellow")
    local blue=$(read_toml "$theme_file" "colors.terminal" "blue")
    local magenta=$(read_toml "$theme_file" "colors.terminal" "magenta")
    local cyan=$(read_toml "$theme_file" "colors.terminal" "cyan")
    local white=$(read_toml "$theme_file" "colors.terminal" "white")
    local bright_black=$(read_toml "$theme_file" "colors.terminal" "bright_black")
    local bright_red=$(read_toml "$theme_file" "colors.terminal" "bright_red")
    local bright_green=$(read_toml "$theme_file" "colors.terminal" "bright_green")
    local bright_yellow=$(read_toml "$theme_file" "colors.terminal" "bright_yellow")
    local bright_blue=$(read_toml "$theme_file" "colors.terminal" "bright_blue")
    local bright_magenta=$(read_toml "$theme_file" "colors.terminal" "bright_magenta")
    local bright_cyan=$(read_toml "$theme_file" "colors.terminal" "bright_cyan")
    local bright_white=$(read_toml "$theme_file" "colors.terminal" "bright_white")

    cat > "$output_file" << EOF
-- Auto-generated by set-theme.sh - DO NOT EDIT
return {
  foreground = "#$fg",
  background = "#$bg",
  cursor_bg = "#$cursor_bg",
  cursor_fg = "#$cursor_fg",
  selection_bg = "#$sel_bg",
  selection_fg = "#$sel_fg",
  ansi = { "#$black", "#$red", "#$green", "#$yellow", "#$blue", "#$magenta", "#$cyan", "#$white" },
  brights = { "#$bright_black", "#$bright_red", "#$bright_green", "#$bright_yellow", "#$bright_blue", "#$bright_magenta", "#$bright_cyan", "#$bright_white" },
}
EOF
}
