unbind C-b
set -g prefix C-a
bind C-a send-prefix
set -g repeat-time 600

bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

bind -r h resize-pane -L 3
bind -r j resize-pane -D 3
bind -r k resize-pane -U 3
bind -r l resize-pane -R 3

set -g mouse on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
setw -g mode-keys vi
set -g bell-action none
set -g visual-bell off
set -g monitor-activity off

set -g status-left "#S"
set -g status-right "#H | %Y-%m-%d %H:%M"
set -g status-left-length 20
set -g status-right-length 50

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -as terminal-features ",wezterm:RGB"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

run '~/.tmux/plugins/tpm/tpm'
