#!/bin/bash
# Syncs themes and wallpapers from this repo to Windows locations

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Auto-detect Windows username
WIN_USER=$(cmd.exe /c 'echo %USERNAME%' 2>/dev/null | tr -d '\r')
if [ -z "$WIN_USER" ]; then
    echo "Error: Could not detect Windows username"
    exit 1
fi

WIN_WALLPAPERS="/mnt/c/Users/$WIN_USER/Pictures/Wallpapers"
WIN_SCRIPTS="/mnt/c/Users/$WIN_USER/scripts/config/themes"
WIN_ZEBAR="/mnt/c/Users/$WIN_USER/AppData/Roaming/zebar/downloads/glzr-io.starter@0.0.0"
WSL_THEMES="$HOME/.config/themes"
WSL_DOTFILES="$HOME/.config/dotfiles"

# Create destination directories
mkdir -p "$WIN_WALLPAPERS" "$WIN_SCRIPTS" "$WSL_THEMES"

echo "Syncing themes..."

# Copy TOML files to WSL config (for set-theme.sh)
cp "$SCRIPT_DIR/themes/"*.toml "$WSL_THEMES/"
echo "  - theme definitions (copied to ~/.config/themes/)"

# Convert TOML to INI for AHK consumption
convert_toml_to_ini() {
    local toml_file="$1"
    local ini_file="$2"

    python3 << EOF
import tomllib
import configparser
from pathlib import Path

toml_path = Path("$toml_file")
ini_path = Path("$ini_file")

with open(toml_path, 'rb') as f:
    data = tomllib.load(f)

config = configparser.ConfigParser()
for section, values in data.items():
    if isinstance(values, dict):
        # Flatten nested dicts for INI format
        flat_values = {}
        for k, v in values.items():
            if isinstance(v, dict):
                # Skip nested dicts (like colors.terminal, colors.base16)
                continue
            flat_values[k] = str(v)
        if flat_values:
            config[section] = flat_values

with open(ini_path, 'w') as f:
    config.write(f)
EOF
}

# Convert each theme TOML to INI
theme_count=0
for toml_file in "$SCRIPT_DIR/themes/"*.toml; do
    if [[ -f "$toml_file" ]]; then
        filename=$(basename "$toml_file" .toml)
        ini_file="$WIN_SCRIPTS/${filename}.ini"
        convert_toml_to_ini "$toml_file" "$ini_file"
        ((theme_count++))
    fi
done
echo "  - AHK theme files ($theme_count themes converted to INI)"

# Generate Zebar CSS for default theme (mocha)
generate_zebar_css() {
    local theme_file="$1"
    local output_file="$2"

    python3 << EOF
import tomllib
from pathlib import Path

theme_path = Path("$theme_file")
output_path = Path("$output_file")

with open(theme_path, 'rb') as f:
    data = tomllib.load(f)

base16 = data['colors']['base16']

css = """/* Auto-generated by theme sync - DO NOT EDIT */
:root {
  --base00: #%s;
  --base01: #%s;
  --base02: #%s;
  --base03: #%s;
  --base04: #%s;
  --base05: #%s;
  --base06: #%s;
  --base07: #%s;
  --base08: #%s;
  --base09: #%s;
  --base0A: #%s;
  --base0B: #%s;
  --base0C: #%s;
  --base0D: #%s;
  --base0E: #%s;
  --base0F: #%s;
}
""" % (
    base16['base00'], base16['base01'], base16['base02'], base16['base03'],
    base16['base04'], base16['base05'], base16['base06'], base16['base07'],
    base16['base08'], base16['base09'], base16['base0A'], base16['base0B'],
    base16['base0C'], base16['base0D'], base16['base0E'], base16['base0F']
)

output_path.parent.mkdir(parents=True, exist_ok=True)
with open(output_path, 'w') as f:
    f.write(css)
EOF
}

# Generate Zebar CSS from default theme
default_theme="$WSL_THEMES/catppuccin-mocha.toml"
if [[ -f "$default_theme" ]] && [[ -d "$WIN_ZEBAR" ]]; then
    generate_zebar_css "$default_theme" "$WIN_ZEBAR/theme-vars.css"
    echo "  - Zebar CSS variables (default theme)"
fi

# Sync wallpapers
echo "Syncing wallpapers to $WIN_WALLPAPERS..."
cp "$SCRIPT_DIR/walls/"*.{png,jpg,jpeg} "$WIN_WALLPAPERS/" 2>/dev/null || true
wallpaper_count=$(ls -1 "$SCRIPT_DIR/walls/"*.{png,jpg,jpeg} 2>/dev/null | wc -l)
echo "  - wallpapers ($wallpaper_count files)"

echo ""
echo "Done! Themes and wallpapers synced."
